px4_dds_bridge:
  ros__parameters:
    dds_domain_id: 0
    px4_uav_id: 0
    command_rate_hz: 50.0

rover_speed_steering_mode:
  ros__parameters:
    skip_message_compatibility_check: true
    use_stamped: true

rover_speed_attitude_mode:
  ros__parameters:
    skip_message_compatibility_check: true
    use_stamped: true

rover_speed_rate_mode:
  ros__parameters:
    skip_message_compatibility_check: true
    use_stamped: true

rover_manual_mode:
  ros__parameters:
    skip_message_compatibility_check: true
    use_stamped: true
    bidirectional_esc: false
